### ISSUE TITLE
No pointer when selecting behind an image

### ISSUE THREAD

**Issue by Vladik01-11** [bluescan/tacit-texview#181]
If "Show Images Tiled" will be active, then selecting some point not on the main image, the pointer will be shown on the main image. (normal)
![image](https://github.com/user-attachments/assets/20aab29f-1273-43d6-bf13-9173e7ae2427)

However, by turning off "Show Images Tiled", there will be no pointer, but the Cursor and Color from the selected pixel will be updated (in my case the edge in X and the current height in Y) (not normal).
![image](https://github.com/user-attachments/assets/07e82680-215d-41c2-a74d-356675055126)

Fix to have the pointer on the edge of the image (probably more correct) or as with "Show Images Tiled" enabled

**Comment by bluescan** [comment]
What you're suggesting makes sense... you can only select pixels essentially in the main image rather than the tiles around it. The other option is to allow selection outside but when turning tiling off don't 'go to the edge' but rather keep the proper relative location. I'll take a look at this when I can. Thanks for the report.

**Comment by bluescan** [comment]
Hmm. I'm having difficulty repo'ing this. Under Preferences->Interface what is the Reticle Mode set to? Is this on Windows or Linux? Are you at the latest version of the viewer and are you using ctrl-T or pressing the tile button to turn off tiling?
 For me the reticle remains visible when I turn off tiling.

**Comment by bluescan** [comment]
Give cb6796f100ad6e1f410d00c77bc4fe61ba77d482 a go.
"Changed OnSelect reticle behaviour to not update the cursor position when a position outside the image is selected. A right-click or cursor-move (shift dir-key) will make the reticle visible again."

It's more along the lines of just doing the part you suggested: 'data doesn't change at all' rather than hiding the colour swatches etc. This also has the benefit that if you are editing a pixel, you can now click outside the image to hide the reticle and adjust the colour without being distracted by the reticle cross (or outline if zoomed in).

If you want the reticle visible again without selecting another pixel, just right-click.
